name = "spf-mcp"
main = "src/index.ts"
compatibility_date = "2025-09-01"

[[d1_databases]]
binding = "DB"
database_name = "spf_db"
database_id = "cf149b95-de59-482d-82ba-4b9a8a356acf"

[[kv_namespaces]]
binding = "SPFKV"
id = "242e0dff16b64732bef9624b08fcffb0"

[[r2_buckets]]
binding = "R2"
bucket_name = "spf-media"

[[durable_objects.bindings]]
name = "CombatDO"
class_name = "CombatDO"

[[durable_objects.bindings]]
name = "DeckDO"
class_name = "DeckDO"

[[durable_objects.bindings]]
name = "RngDO"
class_name = "RngDO"

[[durable_objects.bindings]]
name = "SessionDO"
class_name = "SessionDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CombatDO", "DeckDO", "RngDO", "SessionDO"]

[vars]
MCP_SERVER_NAME = "spf-mcp"
JWT_SECRET = "your-super-secret-jwt-key-change-in-production"
API_KEY = "your-api-key-for-mcp-clients"
